<a href="https://colab.research.google.com/github/Stefan-Physics/for-fun/blob/main/Practice_1_12_29_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hi")
import numpy as np
import matplotlib.pyplot as plt

hi


In [7]:
from IPython.lib.security import random
#to think about if one were meta solve (a + b)/ c
f = np.random.rand()
a = float(f)

b = float(input("b is "))
c = eval(input("c is ")) #how to make it take inputs without putting the .0 afterward

e = a*b
if c == 0:
  print("solution is undefined")
elif e ==0:
  print("solution is 0")
else:
  d = (a + b)/ c
  print(d)
  print(d)


KeyboardInterrupt: ignored

In [ ]:
a = np.random.rand(2,5)
print(a)
for pice in a:
  print (2*pice)

for tpice in ["Max", "Molly", "Buster", "Maggie", "Lucy"]:
  print (2*tpice)

[[0.22059123 0.26833363 0.91586503 0.43523151 0.46888078]
 [0.10564501 0.44124301 0.31561526 0.4715396  0.67444165]]
[0.44118247 0.53666726 1.83173005 0.87046301 0.93776156]
[0.21129001 0.88248602 0.63123053 0.9430792  1.34888331]
MaxMax
MollyMolly
BusterBuster
MaggieMaggie
LucyLucy


In [ ]:
a = np.random.randn()

iq = a*15 + 100
iq

93.47354398455407

In [ ]:
#for
s = 0
for i in range(1,100,2):
  s = s + i
print(s)

2500


In [ ]:
z = 0
x = [1,2,3,4]
for i in range(1,10,1):
  z = z + i
print(z)

45


In [45]:
x = np.linspace(0,2*np.pi,3)

def sinc(x):
    y = []              
    for xx in x:        
        if xx==0.0:     
            y += [1.0]  
        else:           
            y += [np.sin(xx)/xx]
    return np.array(y)
#print(sinc(11))
#x = np.linspace(-10, 10, 256)

y = sinc(x)
print(sinc(x))
#plt.plot(x,y)
#plt.show()

[ 1.00000000e+00  3.89817183e-17 -3.89817183e-17]


In [ ]:
#while
a = 0
while a < 10:
  print (a)
  a += 1


0
1
2
3
4
5
6
7
8
9


In [ ]:
numberinput = eval(input("give a postive integer"))
def FactorialW(numberinput):
  y = numberinput
  if numberinput < 0:
    print ("naw fam")
  elif numberinput == 0:
    print ("no shot")
  else:
    while numberinput > 1:
      numberinput, y = numberinput-1, (numberinput-1)*y
      print (y)

  return y

FactorialW(numberinput)

print("block")

def FactorialF(numberinput):
  x=1
  if numberinput < 0:
    print ("naw fam")
  elif numberinput == 0:
    print ("no shot")
  else:
    for i in range (1, numberinput+1,1):
      print (x)
      x *= i
      i+1
      
  return x

FactorialF(numberinput)
